on:
  push:
    branches: master

jobs:
  test-tweets:
    runs-on: ubuntu-18.04
    container: rocker/tidyverse
    env:
      TW_API_KEY: ${{ secrets.TWITTER_API_KEY }}
      TW_SECRET_KEY: ${{ secrets.TWITTER_SECRET_KEY }}
      TW_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TW_SECRET_TOKEN: ${{ secrets.TWITTER_SECRET_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: |
          remotes::install_cran(c("rtweet", "googlesheets4"))
          remotes::install_github("rfortherestofus/rrutweets")
        shell: Rscript {0}

      - name: Run script
        run: |-
          Rscript inst/test-tweets.R

